<?xml version="1.0" encoding="UTF-8"?>
<!--
  RankRocket SEO Control Layer — Sitemap XSL Stylesheet
  Served by rmb_serve_sitemap_xsl(); RRSEO_* tokens are replaced by PHP before output.
  Handles two document types:
    <sitemapindex> — renders a table of sub-sitemaps
    <urlset>       — renders a table of URLs with lastmod and priority
-->
<xsl:stylesheet version="1.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<title>XML Sitemap &#8212; RRSEO_SITE_NAME</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">
		*  { box-sizing: border-box; }
		body {
			font-size: 14px;
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
				Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			margin: 0;
			color: #333;
			background: #f0f2f5;
		}
		a { color: #3498db; text-decoration: none; }
		a:hover { text-decoration: underline; }
		h1 { font-size: 22px; font-weight: 400; margin: 0 0 8px; }
		#rrseo-header {
			background: #2c3e50;
			padding: 24px 32px 20px;
			color: #fff;
		}
		#rrseo-header h1,
		#rrseo-header p,
		#rrseo-header a { color: #fff; }
		#rrseo-header p {
			margin: 6px 0 0;
			font-size: 13px;
			opacity: .85;
			line-height: 1.5;
		}
		#rrseo-header a { border-bottom: 1px dotted rgba(255,255,255,0.55); }
		#rrseo-content {
			max-width: 1100px;
			margin: 24px auto;
			padding: 24px 32px;
			background: #fff;
			border-radius: 4px;
			box-shadow: 0 1px 4px rgba(0,0,0,.08);
		}
		.rrseo-meta {
			font-size: 13px;
			color: #666;
			margin: 0 0 16px;
		}
		.rrseo-back {
			display: inline-block;
			font-size: 13px;
			margin-bottom: 14px;
		}
		table {
			border-collapse: collapse;
			font-size: 13px;
			width: 100%;
		}
		th {
			background: #2c3e50;
			color: #fff;
			text-align: left;
			padding: 11px 12px;
			font-weight: 500;
			font-size: 12px;
			letter-spacing: .04em;
			text-transform: uppercase;
		}
		td {
			padding: 9px 12px;
			border-bottom: 1px solid #edf0f2;
			vertical-align: middle;
		}
		tbody tr:nth-child(even) { background: #f8f9fa; }
		tbody tr:hover { background: #eef4fb; }
		td a { word-break: break-all; }
		.rrseo-pri {
			display: inline-block;
			padding: 2px 8px;
			border-radius: 10px;
			font-size: 11px;
			font-weight: 600;
			background: #e8f4fd;
			color: #2471a3;
		}
		#rrseo-footer {
			max-width: 1100px;
			margin: 0 auto 24px;
			padding: 10px 32px;
			font-size: 11px;
			color: #aaa;
		}
		#rrseo-footer a { color: #aaa; }
	</style>
</head>
<body>

<div id="rrseo-header">
	<h1>XML Sitemap &#8212; RRSEO_SITE_NAME</h1>
	<p>
		Generated by
		<a href="https://rankrocket.co" target="_blank">RankRocket SEO Control Layer</a>.
		XML Sitemaps tell search engines which pages to crawl and how often.
		<a href="https://www.sitemaps.org/protocol.html" target="_blank">Learn more about the Sitemap protocol.</a>
	</p>
</div>

<div id="rrseo-content">

	<!-- ── Sitemap Index view ─────────────────────────────────────────── -->
	<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
		<p class="rrseo-meta">
			This sitemap index contains
			<strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong>
			sub-sitemap(s). Click any entry to view its URLs.
		</p>
		<table>
			<thead>
				<tr>
					<th width="75%">Sub-Sitemap</th>
					<th width="25%">Last Modified</th>
				</tr>
			</thead>
			<tbody>
				<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
					<tr>
						<td>
							<a href="{sitemap:loc}">
								<xsl:value-of select="sitemap:loc"/>
							</a>
						</td>
						<td>
							<xsl:value-of select="concat(
								substring(sitemap:lastmod, 0, 11), ' ',
								substring(sitemap:lastmod, 12, 5), ' UTC')"/>
						</td>
					</tr>
				</xsl:for-each>
			</tbody>
		</table>
	</xsl:if>

	<!-- ── URL list view ─────────────────────────────────────────────── -->
	<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
		<a class="rrseo-back" href="RRSEO_INDEX_URL">&#8592; Back to Sitemap Index</a>
		<p class="rrseo-meta">
			This sitemap contains
			<strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong>
			URL(s).
		</p>
		<table>
			<thead>
				<tr>
					<th width="70%">URL</th>
					<th width="20%">Last Modified</th>
					<th width="10%">Priority</th>
				</tr>
			</thead>
			<tbody>
				<xsl:for-each select="sitemap:urlset/sitemap:url">
					<tr>
						<td>
							<a href="{sitemap:loc}">
								<xsl:value-of select="sitemap:loc"/>
							</a>
						</td>
						<td>
							<xsl:value-of select="concat(
								substring(sitemap:lastmod, 0, 11), ' ',
								substring(sitemap:lastmod, 12, 5), ' UTC')"/>
						</td>
						<td>
							<span class="rrseo-pri">
								<xsl:value-of select="sitemap:priority"/>
							</span>
						</td>
					</tr>
				</xsl:for-each>
			</tbody>
		</table>
	</xsl:if>

</div>

<div id="rrseo-footer">
	RankRocket SEO Control Layer v RRSEO_VERSION &#8212;
	<a href="https://rankrocket.co" target="_blank">rankrocket.co</a>
</div>

</body>
</html>
</xsl:template>

</xsl:stylesheet>
